/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.kgromov.schema.events;

@org.apache.avro.specific.AvroGenerated
public interface OrderCreatedEvent {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OrderCreatedEvent\",\"namespace\":\"org.kgromov.schema.events\",\"types\":[{\"type\":\"record\",\"name\":\"OrderCreatedEvent\",\"fields\":[{\"name\":\"orderNumber\",\"type\":\"long\"},{\"name\":\"food\",\"type\":\"string\"},{\"name\":\"quantity\",\"type\":\"int\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends OrderCreatedEvent {
    public static final org.apache.avro.Protocol PROTOCOL = org.kgromov.schema.events.OrderCreatedEvent.PROTOCOL;
  }
}