/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package org.kgromov.schema.events;

@org.apache.avro.specific.AvroGenerated
public interface OrderPlacedEvent {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"OrderPlacedEvent\",\"namespace\":\"org.kgromov.schema.events\",\"types\":[{\"type\":\"record\",\"name\":\"OrderPlacedEvent\",\"fields\":[{\"name\":\"orderNumber\",\"type\":\"long\"},{\"name\":\"email\",\"type\":\"string\"},{\"name\":\"firstName\",\"type\":\"string\"},{\"name\":\"lastName\",\"type\":\"string\"}]}],\"messages\":{}}");

  @org.apache.avro.specific.AvroGenerated
  public interface Callback extends OrderPlacedEvent {
    public static final org.apache.avro.Protocol PROTOCOL = org.kgromov.schema.events.OrderPlacedEvent.PROTOCOL;
  }
}